# Generated by Django 4.2.2 on 2023-06-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_runner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
