# Generated by Django 4.2.2 on 2023-06-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_runner', '0002_codesnippet_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnippet',
            name='status',
        ),
    ]
