# Generated by Django 4.2.2 on 2023-06-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_runner', '0003_remove_codesnippet_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnippet',
            name='output',
        ),
    ]
