# Generated by Django 4.2.2 on 2023-06-25 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('code_runner', '0004_remove_codesnippet_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='errors',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='output',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='code',
            field=models.TextField(default=''),
        ),
    ]
