# Generated by Django 4.2.2 on 2023-06-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_runner', '0005_codesnippet_created_at_codesnippet_errors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codesnippet',
            old_name='output',
            new_name='user_input',
        ),
        migrations.RemoveField(
            model_name='codesnippet',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='codesnippet',
            name='errors',
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='code',
            field=models.TextField(),
        ),
    ]
