# Generated by Django 4.2.2 on 2023-06-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_runner', '0006_rename_output_codesnippet_user_input_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeSnippet',
        ),
    ]
